# Generated by Django 4.2.1 on 2023-06-27 21:16

from django.db import migrations, models
import extraction.models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to=extraction.models.update_filename),
        ),
    ]
